### ISSUE TITLE
Moment not working as a dependancy with ES6

### ISSUE THREAD

**Issue by linnett** [Pikaday/Pikaday#625]
I import Pikaday into my ES6 module but I also want to use the moment.js feature to format the date. We're using npm manage dependancies within our components, so referencing the `node_modules` directly:
```
import moment from './node_modules/moment/moment';
import Pikaday from './node_modules/pikaday/pikaday';
```
If I `console.log(moment)`  below these imports, moment JS is loaded. However, it does not exist in Pikaday as it is not a dependancy. How do I get Pikaday to recognise it as a dependancy so I can use moment?

**Comment by PhiLhoSoft** [comment]
It is a problem with these libraries designed to go in the global context...
I had a similar problem with loading jQuery before AngularJS, so that the latter uses it instead of jq.
This specific problem was resolved by Stack Overflow: http://stackoverflow.com/questions/36065931/webpack-how-to-make-angular-auto-detect-jquery-and-use-it-as-angular-element-in
But it is a Webpack-specific solution, so I don't know if you can use it, but perhaps it can push you in the right direction...

**Comment by wojciechczerniak** [comment]
We will drop moment.js dependency. Duplicate of #815

**Comment by atilkan** [comment]
@wojciechczerniak The problem is also that it doesn't work in webpack environment.
